import { saveCampaign, getCampaign, listCampaigns } from "./campaign-tools";
import {
  searchCompanies,
  discoverCompanies,
  getCompanies,
  getCompanyDetail,
  getCampaignSummary,
  searchYCCompanies,
} from "./search-tools";
import {
  searchPeople,
  enrichContact,
  extractWebContent,
  fetchSitemap,
  getContacts,
  getContactDetail,
  enrichCompany,
  enrichCompanies,
  enrichContacts,
  findContacts,
  deleteCompanies,
  deleteContacts,
  scrapeJobListings,
  scrapeJobListingsBatch,
  scoreCompany,
  scoreContact,
  updateCompanyStatus,
  getGoogleReviews,
} from "./enrichment-tools";
import {
  getUserProfile,
  updateUserProfile,
  listProfiles,
} from "./profile-tools";
import {
  getSignalAuthoringGuide,
  testSignalRecipe,
  getSignals,
  getSignalDetail,
  getCampaignSignals,
  toggleCampaignSignal,
  createSignal,
  updateSignal,
  makeSignalPublic,
  getSignalResults,
} from "./signal-tools";
import {
  fetchGitHubStargazers,
  enrichGitHubProfiles,
  searchGitHubRepos,
} from "./github-tools";
import {
  createTracking,
  bulkCreateTracking,
  getTrackingConfigs,
  getTrackingHistory,
  updateTracking,
} from "./tracking-tools";
import {
  findEmail,
  findEmails,
  writeEmail,
  sendEmail,
  sendBulkEmails,
  listDrafts,
  discardDraft,
} from "./email-tools";
import {
  createSequence,
  draftSequenceEmails,
  draftEmailsForSequence,
  getSequenceStatus,
} from "./sequence-tools";
import {
  listEmailSkills,
  getEmailSkillDetail,
  createEmailSkill,
  updateEmailSkill,
  deleteEmailSkill,
  toggleEmailSkill,
} from "./email-skill-tools";

export const allTools = {
  saveCampaign,
  getCampaign,
  listCampaigns,
  searchCompanies,
  discoverCompanies,
  getCompanies,
  getCompanyDetail,
  getCampaignSummary,
  searchYCCompanies,
  searchPeople,
  enrichContact,
  extractWebContent,
  fetchSitemap,
  getContacts,
  getContactDetail,
  getUserProfile,
  updateUserProfile,
  listProfiles,
  enrichCompany,
  enrichCompanies,
  enrichContacts,
  findContacts,
  deleteCompanies,
  deleteContacts,
  scrapeJobListings,
  scrapeJobListingsBatch,
  scoreCompany,
  scoreContact,
  updateCompanyStatus,
  getGoogleReviews,
  getSignalAuthoringGuide,
  testSignalRecipe,
  getSignals,
  getSignalDetail,
  getCampaignSignals,
  toggleCampaignSignal,
  createSignal,
  updateSignal,
  makeSignalPublic,
  getSignalResults,
  fetchGitHubStargazers,
  enrichGitHubProfiles,
  searchGitHubRepos,
  createTracking,
  bulkCreateTracking,
  getTrackingConfigs,
  getTrackingHistory,
  updateTracking,
  findEmail,
  findEmails,
  writeEmail,
  sendEmail,
  sendBulkEmails,
  listDrafts,
  discardDraft,
  createSequence,
  draftSequenceEmails,
  draftEmailsForSequence,
  getSequenceStatus,
  listEmailSkills,
  getEmailSkillDetail,
  createEmailSkill,
  updateEmailSkill,
  deleteEmailSkill,
  toggleEmailSkill,
};
